#!/bin/bash

# You don't need to edit this file, this file gets populated from docker args on build

P4_SUPER_USER=REPLACE_WITH_SUPER_USER
P4_SUPER_PASSWORD=REPLACE_WITH_SUPER_PASSWORD
P4_STREAM_NAME=REPLACE_WITH_STREAM_NAME
P4_SERVER_WORKSPACE_NAME=REPLACE_WITH_SERVER_WORKSPACE_NAME

export P4USER=$P4_SUPER_USER
export P4PASSWD=$P4_SUPER_PASSWORD
